### ISSUE TITLE
Fix: "Fatal - Unknown CA"

### ISSUE THREAD

**Issue by indutny** [indutny/funnel#2]
When connecting to google's smtp server:

```
02:12:35.914 [error] GenServer #PID<0.311.0> terminating
** (MatchError) no match of right hand side value: {:error, {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1895 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}
    (funnel 0.1.0) lib/funnel/client/connection.ex:104: Funnel.Client.Connection.handle_call/3
    (stdlib 3.14.1) gen_server.erl:715: :gen_server.try_handle_call/4
    (stdlib 3.14.1) gen_server.erl:744: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.312.0>): :starttls
State: {%Funnel.Client.Config{connect_timeout: 60000, host: "indutny.com", insecure: false, local_domain: "smtp.mean.engineer", lookup_fun: {&Funnel.Client.lookup/1, []}, max_line_size: 512, port: 25, read_timeout: 300000}, [[packet: :line, packet_size: 512, active: false, versions: [:"tlsv1.2", :"tlsv1.3"], ciphers: [{:ecdhe_ecdsa, :chacha20_poly1305, :aead, :sha256}, {:ecdhe_rsa, :chacha20_poly1305, :aead, :sha256}, {:ecdhe_ecdsa, :aes_256_gcm, :aead, :sha384}, {:ecdhe_rsa, :aes_256_gcm, :aead, :sha384}, {:ecdhe_ecdsa, :aes_256_cbc, :sha384, :sha384}, {:ecdhe_rsa, :aes_256_cbc, :sha384, :sha384}, {:ecdhe_ecdsa, :aes_128_gcm, :aead, :sha256}, {:ecdhe_rsa, :aes_128_gcm, :aead, :sha256}, {:ecdhe_ecdsa, :aes_128_cbc, :sha256, :sha256}, {:ecdhe_rsa, :aes_128_cbc, :sha256, :sha256}, {:dhe_rsa, :chacha20_poly1305, :aead, :sha256}, {:dhe_rsa, :aes_256_gcm, :aead, :sha384}, {:dhe_rsa, :aes_256_cbc, :sha256}, {:dhe_rsa, :aes_128_gcm, :aead, :sha256}, {:dhe_rsa, :aes_128_cbc, :sha256}, {:any, :chacha20_poly1305, :aead, :sha256}, {:any, :aes_256_gcm, :aead, :sha384}, {:any, :aes_128_gcm, :aead, :sha256}], server_name_indication: 'aspmx.l.google.com', reuse_sessions: false], {:verify_fun, {&:ssl_verify_hostname.verify_fun/3, [check_hostname: 'aspmx.l.google.com']}}, {:verify, :verify_peer}], :gen_tcp, #Port<0.12>}
Client #PID<0.312.0> is alive

    (stdlib 3.14.1) gen.erl:208: :gen.do_call/4
    (elixir 1.11.2) lib/gen_server.ex:1024: GenServer.call/3
    (funnel 0.1.0) lib/funnel_smtp/client.ex:172: FunnelSMTP.Client.starttls/2
    (funnel 0.1.0) lib/funnel_smtp/client.ex:76: FunnelSMTP.Client.handle_call/3
    (stdlib 3.14.1) gen_server.erl:715: :gen_server.try_handle_call/4
    (stdlib 3.14.1) gen_server.erl:744: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by indutny** [comment]
Fixed in https://github.com/indutny/funnel/commit/66f901d249d8b4deb4213899f6970007e521f3a1
